import { useEffect, useState } from "react";

import { Bordes } from "../components/Bordes";
import { Convolucion } from "../components/Convolucion";
import { Foco } from "../components/Foco";
import Head from "next/head";
import { Histograma } from "../components/Histograma";
import { NavBar } from "../components/NavBar";
import { Operadores } from "../components/Operadores";
import { RGB } from "../components/RGB";
import { Scala } from "../components/Scala";

export default function Home() {
  const [toolSelected, setToolSelected] = useState("RGB");

  useEffect(() => {
    const toolInCookie = localStorage.getItem('toolSelected');
    if (toolInCookie) {
      setToolSelected(toolInCookie)
    }
  }, []);

  return (
    <div className="">
      <Head>
        <title>PDI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar setMode={setToolSelected} toolSelected={toolSelected} />
      <div className="pt-24">
        <div>{toolSelected == "Bordes" && <Bordes />}</div>
        <div>{toolSelected == "RGB" && <RGB />}</div>
        <div>{toolSelected == "Operadores" && <Operadores />}</div>
        <div>{toolSelected == "Convolucion" && <Convolucion />}</div>
        <div>{toolSelected == "Foco" && <Foco />}</div>
        <div>{toolSelected == "Histograma" && <Histograma />}</div>
        <div>{toolSelected == "Scala" && <Scala />}</div>
      </div>
    </div>
  );
}
